apiVersion: automation.actions.pagerduty.crossplane.io/v1alpha1
kind: ActionTeamAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: automation/v1alpha1/actionteamassociation
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    actionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: pa_action_example
    teamIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: automation.actions.pagerduty.crossplane.io/v1alpha1
kind: Action
metadata:
  annotations:
    meta.upbound.io/example-id: automation.actions/v1alpha1/actionteamassociation
  labels:
    testing.upbound.io/example-name: pa_action_example
  name: pa-action-example
spec:
  forProvider:
    actionDataReference:
    - processAutomationJobId: P123456
    actionType: process_automation
    description: Description of the PA Action created via TF
    name: PA Action created via TF

---

apiVersion: team.pagerduty.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: automation.actions/v1alpha1/actionteamassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: All engineering
    name: Engineering
