apiVersion: escalation.pagerduty.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: escalation/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Engineering Escalation Policy
    numLoops: 2
    rule:
    - escalationDelayInMinutes: 10
      target:
      - id: ${pagerduty_user.example.id}
        type: user_reference
      - id: ${pagerduty_user.example2.id}
        type: user_reference
    teamRefs:
    - name: example

---

apiVersion: team.pagerduty.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: escalation/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: All engineering
    name: Engineering

---

apiVersion: user.pagerduty.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: escalation/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    email: 125.greenholt.earline@graham.name
    name: Earline Greenholt

---

