apiVersion: user.pagerduty.crossplane.io/v1alpha1
kind: NotificationRule
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/notificationrule
  labels:
    testing.upbound.io/example-name: high_urgency_phone
  name: high-urgency-phone
spec:
  forProvider:
    contactMethod:
      id: ${pagerduty_user_contact_method.phone.id}
      type: phone_contact_method
    startDelayInMinutes: 1
    urgency: high
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: user.pagerduty.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/notificationrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    email: 125.greenholt.earline@graham.name
    name: Earline Greenholt

---

apiVersion: user.pagerduty.crossplane.io/v1alpha1
kind: ContactMethod
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/notificationrule
  labels:
    testing.upbound.io/example-name: email
  name: email
spec:
  forProvider:
    address: foo@bar.com
    label: Work
    type: email_contact_method
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: user.pagerduty.crossplane.io/v1alpha1
kind: ContactMethod
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/notificationrule
  labels:
    testing.upbound.io/example-name: phone
  name: phone
spec:
  forProvider:
    address: "2025550199"
    countryCode: "+1"
    label: Work
    type: phone_contact_method
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: user.pagerduty.crossplane.io/v1alpha1
kind: ContactMethod
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/notificationrule
  labels:
    testing.upbound.io/example-name: sms
  name: sms
spec:
  forProvider:
    address: "2025550199"
    countryCode: "+1"
    label: Work
    type: sms_contact_method
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
