apiVersion: extensions.pagerduty.crossplane.io/v1alpha1
kind: Extension
metadata:
  annotations:
    meta.upbound.io/example-id: extensions/v1alpha1/extension
  labels:
    testing.upbound.io/example-name: slack
  name: slack
spec:
  forProvider:
    config: "{\n\t\"restrict\": \"any\",\n\t\"notify_types\": {\n\t\t\t\"resolve\":
      false,\n\t\t\t\"acknowledge\": false,\n\t\t\t\"assignments\": false\n\t},\n\t\"access_token\":
      \"XXX\"\n}\n"
    endpointUrlSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    extensionObjectsRefs:
    - name: example
    extensionSchema: ${data.pagerduty_extension_schema.webhook.id}
    name: My Web App Extension

---

apiVersion: escalation.pagerduty.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: extensions/v1alpha1/extension
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Engineering Escalation Policy
    numLoops: 2
    rule:
    - escalationDelayInMinutes: 10
      target:
      - id: ${pagerduty_user.example.id}
        type: user

---

apiVersion: service.pagerduty.crossplane.io/v1alpha1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: extensions/v1alpha1/extension
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    acknowledgementTimeout: 600
    autoResolveTimeout: 14400
    escalationPolicySelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: My Web App

---

apiVersion: user.pagerduty.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: extensions/v1alpha1/extension
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    email: howard.james@example.domain
    name: Howard James
