apiVersion: webhook.pagerduty.crossplane.io/v1alpha1
kind: Subscription
metadata:
  annotations:
    meta.upbound.io/example-id: webhook/v1alpha1/subscription
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    active: true
    deliveryMethod:
    - customHeader:
      - name: X-Foo
        value: foo
      - name: X-Bar
        value: bar
      type: http_delivery_method
      url: https://example.com/receive_a_pagerduty_webhook
    description: '%s'
    events:
    - incident.acknowledged
    - incident.annotated
    - incident.delegated
    - incident.escalated
    - incident.priority_updated
    - incident.reassigned
    - incident.reopened
    - incident.resolved
    - incident.responder.added
    - incident.responder.replied
    - incident.status_update_published
    - incident.triggered
    - incident.unacknowledged
    filter:
    - id: ${data.pagerduty_service.example.id}
      type: service_reference
    type: webhook_subscription
