apiVersion: service.pagerduty.crossplane.io/v1alpha1
kind: Integration
metadata:
  annotations:
    meta.upbound.io/example-id: service/v1alpha1/integration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Generic API Service Integration
    serviceSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    type: generic_events_api_inbound_integration

---

apiVersion: escalation.pagerduty.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: service/v1alpha1/integration
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    name: Engineering Escalation Policy
    numLoops: 2
    rule:
    - escalationDelayInMinutes: 10
      target:
      - id: ${pagerduty_user.example.id}
        type: user

---

apiVersion: service.pagerduty.crossplane.io/v1alpha1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: service/v1alpha1/integration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    acknowledgementTimeout: 600
    autoResolveTimeout: 14400
    escalationPolicySelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: My Web App

---

apiVersion: user.pagerduty.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: service/v1alpha1/integration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    email: 125.greenholt.earline@graham.name
    name: Earline Greenholt
